### ISSUE TITLE
Locking up at Building and writing VMX file

### ISSUE THREAD

**Issue by ghost** [chrisipa/packer-esxi#3]
The process makes it to Building and writing VMX file and then locks up.  I cannot break out and have to close the session.  I have verified that the OS disk has been created in ESXi.

**Comment by chrisipa** [comment]
Can you please post a log of your shell execution here. This would make this a lot of easier to debug on my end.

**Comment by chrisipa** [comment]
Closed due to inactivity ...

**Comment by thusc** [comment]
I had the same problem (posting the hanging line to help others find this):

```
==> some-vm-name: Building and writing VMX file
```

It was fixed by following the section "Open VNC Ports on the Firewall" in this post: https://nickcharlton.net/posts/using-packer-esxi-6.html

**Comment by chrisipa** [comment]
@thusc Ok that's interesting. I have also documented the opening of firewall ports here:

https://github.com/chrisipa/packer-esxi#allow-network-communication-for-packer

Did you try my instructions? Maybe I have to work on the documentation to make it more user friendly.

**Comment by thusc** [comment]
@chrisipa No I didn't know about your repository.

In my use case, I think I would like to use something like cloud-init to configure the VM, instead of doing everything at Packer-time.
